CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    genre VARCHAR(50) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    CONSTRAINT chk_movies_duration_positive
        CHECK (duration_minutes > 0)
);