spring.application.name=payment-service
server.port=8085

management.endpoints.web.exposure.include=health,info
spring.mvc.problemdetails.enabled=true

spring.datasource.url=${PAYMENT_DB_URL:jdbc:postgresql://localhost:5437/payment_db}
spring.datasource.username=${PAYMENT_DB_USERNAME:payment_user}
spring.datasource.password=${PAYMENT_DB_PASSWORD:payment_local_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:cinema}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:cinema_local_password}

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1s
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.default-requeue-rejected=false