CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE halls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    row_count INTEGER NOT NULL,
    seats_per_row INTEGER NOT NULL,

    CONSTRAINT chk_hall_rows
        CHECK (row_count BETWEEN 1 AND 26),

    CONSTRAINT chk_hall_seats_per_row
        CHECK (seats_per_row BETWEEN 1 AND 50)
);

CREATE TABLE screenings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL,
    hall_id BIGINT NOT NULL REFERENCES halls(id),
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ticket_price NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,

    CONSTRAINT chk_screening_movie_id
        CHECK (movie_id > 0),

    CONSTRAINT chk_screening_times
        CHECK (ends_at > starts_at),

    CONSTRAINT chk_screening_price
        CHECK (ticket_price > 0),

    CONSTRAINT chk_screening_currency
        CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT no_overlapping_screenings
        EXCLUDE USING gist (
            hall_id WITH =,
            tstzrange(starts_at, ends_at, '[)') WITH &&
        )
);

CREATE INDEX idx_screenings_movie_start
    ON screenings (movie_id, starts_at);