spring.application.name=screening-service
server.port=8082

management.endpoints.web.exposure.include=health,info

spring.datasource.url=${SCREENING_DB_URL:jdbc:postgresql://localhost:5434/screening_db}
spring.datasource.username=${SCREENING_DB_USERNAME:screening_user}
spring.datasource.password=${SCREENING_DB_PASSWORD:screening_local_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

clients.movie-service.url=${MOVIE_SERVICE_URL:http://localhost:8081}
spring.mvc.problemdetails.enabled=true

eureka.client.enabled=${EUREKA_ENABLED:false}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.cloud.config.enabled=${CONFIG_ENABLED:false}
spring.config.import=${CONFIG_IMPORT:}