spring.application.name=discovery-server
server.port=8761

management.endpoints.web.exposure.include=health,info

eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/