spring.application.name=reservation-service
server.port=8084

management.endpoints.web.exposure.include=health,info
spring.mvc.problemdetails.enabled=true

spring.datasource.url=${RESERVATION_DB_URL:jdbc:postgresql://localhost:5436/reservation_db}
spring.datasource.username=${RESERVATION_DB_USERNAME:reservation_user}
spring.datasource.password=${RESERVATION_DB_PASSWORD:reservation_local_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:cinema}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:cinema_local_password}

clients.screening-service.url=${SCREENING_SERVICE_URL:http://localhost:8082}
clients.inventory-service.url=${INVENTORY_SERVICE_URL:http://localhost:8083}