spring.application.name=movie-service
server.port=8081

management.endpoints.web.exposure.include=health,info

spring.datasource.url=${MOVIE_DB_URL:jdbc:postgresql://localhost:5433/movie_db}
spring.datasource.username=${MOVIE_DB_USERNAME:movie_user}
spring.datasource.password=${MOVIE_DB_PASSWORD:movie_local_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false