spring.application.name=seat-inventory-service
server.port=8083

management.endpoints.web.exposure.include=health,info
spring.mvc.problemdetails.enabled=true

spring.datasource.url=${INVENTORY_DB_URL:jdbc:postgresql://localhost:5435/inventory_db}
spring.datasource.username=${INVENTORY_DB_USERNAME:inventory_user}
spring.datasource.password=${INVENTORY_DB_PASSWORD:inventory_local_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

clients.screening-service.url=${SCREENING_SERVICE_URL:http://localhost:8082}
inventory.hold-duration=PT10M

eureka.client.enabled=${EUREKA_ENABLED:false}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.cloud.config.enabled=${CONFIG_ENABLED:false}
spring.config.import=${CONFIG_IMPORT:}